### ISSUE TITLE
babel madness: typeof -> _typeof -> _typeof4

### ISSUE THREAD

**Issue by elidoran** [meteor-svelte/svelte-es5-meteor#2]
Svelte has this line in its `dispatchObservers` function:

```js
// src/shared/index.js
if ( newValue === oldValue && typeof newValue !== 'object' ) continue;
```

After compiling it to ES5 for package "svelte-es5-meteor" it becomes:

```js
// dist/svelte.js@0.3.0 line 14606
if (newValue === oldValue && 
  (typeof newValue === 'undefined' ? 'undefined' : _typeof(newValue)) !== 'object') 
    continue;
```

Then, after Meteor's build system processes it I get an error saying `_typeof is not defined`.

I checked through the source code it built using View Page Source and found Meteor is changing the use of `typeof`. It grabs that from 'babel/runtime/typeof' and assigns it to `_typeof3` and then does the ES5 interop (`_interopRequireDefault`) thing to make a `_typeof4` with a default property containing it. Then, the later code uses `_typeof4.default` instead of `typeof`.

Except, the "dispatchObservers" function still uses `_typeof`, which doesn't exist. It was defined in svelte but didn't make it into the code sent to the browser.

I then changed the line in `dist/svelte.js` to be the way the original `src/shared/index.js` is. Reset the meteor project and started the app. Then the line looks like this:

```js
if (newValue === oldValue && 
  (typeof newValue === "undefined" ? "undefined" : (0, _typeof3.default)(newValue)) !== 'object')
    continue;
```

It is now replacing the `typeof` use with the `_typeof3` variable Meteor put in there (which was _typeof4 previously). So, it works because that is defined.

It seems to me the transpiling for "svelte-es5-meteor" is changing that line in a way which prevents it from being changed later by Meteor when Meteor tries to replace the `typeof` operations. Or, somehow it's failing to include a declaration creating `_typeof` in the browser code.

Have you encountered this? 

I'm not sure what the fix should be. Is it to avoid transpiling the line used in generating code? Or, ensure `_typeof` is defined in the code sent to the browser?

**Comment by klaussner** [comment]
Thank you for the detailed description! The problem seems to be that I'm using Babel to transpile the complete Svelte package, including the code that is later copied to the generated components. If Babel encounters a `typeof`, it replaces it with a call to `_typeof`, whose definition is also included in the transpiled code. However, Svelte generates code by calling [`Function.prototype.toString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString) on functions like `dispatchObservers` to get their source code. This means that the generated code doesn't include other functions, variables, etc. that are defined outside of the function, such as `_typeof` (which is only in the same scope).

I think avoiding transpilation of these helper functions would be a good solution. It looks like they are all in the [svelte/src/shared](https://github.com/sveltejs/svelte/tree/master/src/shared) directory.

**Comment by klaussner** [comment]
Good news! Svelte is compatible with Node v4 since sveltejs/svelte@55f3ed42d937abf970abd9396821c7eadd88bd33, so we can import `svelte` directly in the build plugin and the `svelte-es5-meteor` package is no longer needed. I've published a patch for the compiler packages on Atmosphere (`svelte:compiler` 1.3.1 and `svelte:compiler-no-html` 1.2.1). `dispatchObservers` and other generated code should work as expected now.
